#!/bin/bash
./mvnw dependency:build-classpath -Dmdep.outputFile=target/classpath -Dmdep.regenerateFile=true -q
echo -n -cp target/classes:> target/cmdargs
cat target/classpath >> target/cmdargs
java @target/cmdargs io.github.arrayv.main.ArrayVisualizer $@
